name: Node.js CI

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 15.x
        uses: actions/setup-node@v3
        with:
          node-version: 15.x
      - run: npm run test
      - if:
          - result != 0
          - name: Fail the workflow
            uses: actions/fail@v1
            with:
              message: "npm run test failed"