name: Node.js CI

on:
  push:
    branches:
      - ci

jobs:
  build:

    runs-on: ubuntu-latest

    # only where the branch is not master
    # and the branch is not develop

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 15.x
        uses: actions/setup-node@v3
        with:
          node-version: 15.x
      - run: npm install
      - run: npm run test

  pull-request:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: pull-request
      uses: repo-sync/pull-request@v2
      with:
        source_branch: "ci"                                 # If blank, default: triggered branch
        destination_branch: "main"                      # If blank, default: master
        pr_title: "Pulling ${{ github.ref }} into main" # Title of pull request
        pr_body: ":crown: *An automated PR*"              # Full markdown support, requires pr_title to be set
        pr_template: ".github/PULL_REQUEST_TEMPLATE.md"   # Path to pull request template, requires pr_title to be set, excludes pr_body
        pr_reviewer: "O4FDev"                         # Comma-separated list (no spaces)
        pr_assignee: "O4FDev"                         # Comma-separated list (no spaces)
        pr_label: "auto-pr"                               # Comma-separated list (no spaces)
        pr_milestone: "Milestone 1"                       # Milestone name
        pr_draft: true                                    # Creates pull request as draft
        pr_allow_empty: true                              # Creates pull request even if there are no changes
        github_token: ${{ secrets.TOKEN }}

  # createpr: 

  #   runs-on: ubuntu-latest

  #   needs: [build]

  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: peter-evans/create-pull-request@v4
  #       with:
  #         base: ci
  #         branch: example-branch
  #         token: ${{ secrets.TOKEN }}
  #         reviewers: O4FDev
  #         assignees: O4FDev
  #         signoff: false
  #         commit-message: Now that the tests have passed, we'll create a pull request!
  #         title: '[Example] Test the application'
  #         body: >
  #           This PR is auto-generated by 
  #           [create-pull-request](https://github.com/peter-evans/create-pull-request).
  #         labels: report, automated pr
      